export type DatabaseRecordItemType =
    "None"
    | "ConflictSolverConfig"
    | "Settings"
    | "Revisions"
    | "Expiration"
    | "PeriodicBackups"
    | "ExternalReplications"
    | "RavenConnectionStrings"
    | "SqlConnectionStrings"
    | "RavenEtls"
    | "SqlEtls"
    | "Client"
    | "Sorters"
    | "SinkPullReplications"
    | "HubPullReplications"
    | "TimeSeries"
    | "DocumentsCompression"
    | "Analyzers"
    | "LockMode"
    | "OlapConnectionStrings"
    | "OlapEtls"
    | "ElasticSearchConnectionStrings"
    | "ElasticSearchEtls"
    | "PostgreSqlIntegration"
    | "QueueConnectionStrings"
    /**
     * @deprecated The server-side enum member is "QueueEtls". Use "QueueEtls" instead.
     */
    | "QueueEtl"
    | "QueueEtls"
    | "IndexesHistory"
    | "Refresh"
    | "QueueSinks"
    | "DataArchival"
    | "SnowflakeConnectionStrings"
    | "SnowflakeEtls"
    | "EmbeddingsGenerations"
    | "AiConnectionStrings"
    | "GenAiEtls"
    | "AiAgents"
    | "RemoteAttachments"
    | "SchemaValidation"
    | "CdcSinks";
