export type DatabaseItemType =
    "None"
    | "Documents"
    | "RevisionDocuments"
    | "Indexes"
    | "Identities"
    | "Tombstones"
    | "LegacyAttachments"
    | "Conflicts"
    | "CompareExchange"
    | "LegacyDocumentDeletions"
    | "LegacyAttachmentDeletions"
    | "DatabaseRecord"
    | "Unknown"
    | "Counters";