export type DatabaseRecordItemType =
    "None"
    | "ConflictSolverConfig"
    | "Settings"
    | "Revisions"
    | "Expiration"
    | "PeriodicBackups"
    | "ExternalReplications"
    | "RavenConnectionStrings"
    | "SqlConnectionStrings"
    | "RavenEtls"
    | "SqlEtls"
    | "Client"
    | "Sorters"
    | "SinkPullReplications"
    | "HubPullReplications"
    | "TimeSeries"
    | "DocumentsCompression"
    | "Analyzers"
    | "LockMode"
    | "OlapConnectionStrings"
    | "OlapEtls";