import { AiConversationResult } from "./AiConversationResult.js";
import { AiAgentActionRequest } from "../Operations/AI/Agents/RunConversationOperation.js";

export interface IAiConversationOperations<T> {
    /**
     * The identifier of this conversation.
     */
    readonly id: string;

    /**
     * The most recent answer generated by the AI agent.
     */
    readonly answer: T;

    /**
     * The current RavenDB change vector for this conversation document,  
     * used to detect concurrent modifications.
     */
    readonly changeVector: string;

    /**
     * Retrieves the list of action-tool requests  
     * that the AI agent needs you to execute.
     */
    requiredActions(): AiAgentActionRequest[];

    /**
     * Adds a string response for a given action request.
     */
    addActionResponse(actionId: string, actionResponse: string): void;

    /**
     * Adds a typed response object for a given action request.
     */
    addActionResponse<TResponse extends object>(actionId: string, actionResponse: TResponse): void;

    /**
     * Executes one "turn" of the conversation:  
     * sends the current prompt, processes any required actions,  
     * and awaits the agent's reply.
     */
    run(token?: AbortSignal): Promise<AiConversationResult>;

    /**
     * Sets the next user prompt to send to the AI agent.
     */
    setUserPrompt(userPrompt: string): void;
}
