import {TypeUtil} from "../Utility/TypeUtil";
import { VError } from "verror";

export function throwError(message: string, errName?: ErrorType, errCause?: Error, info?: { [key: string]: any }) {
  throw new VError({
    name: errName,
    cause: errCause,
    info
  }, message);
}

export type ErrorType = "NotSupportedException"
| "InvalidOperationException"
| "InvalidArgumentException"
| "ErrorResponseException"
| "DocumentDoesNotExistsException"
| "NonUniqueObjectException"
| "ConcurrencyException"
| "ArgumentNullException"
| "ArgumentOutOfRangeException"
| "DatabaseDoesNotExistException"
| "AuthorizationException"
| "IndexDoesNotExistException"
| "DatabaseLoadTimeoutException"
| "AuthenticationException"
| "BadRequestException"
| "BulkInsertAbortedException"
| "BulkInsertProtocolViolationException"
| "IndexCompilationException"
| "TransformerCompilationException"
| "DocumentConflictException"
| "DocumentDoesNotExistException"
| "DocumentParseException"
| "IndexInvalidException"
| "IndexOrTransformerAlreadyExistException"
| "JavaScriptException"
| "JavaScriptParseException"
| "SubscriptionClosedException"
| "SubscriptionDoesNotBelongToNodeException"
| "SubscriptionDoesNotExistException"
| "SubscriptionException"
| "SubscriptionInUseException"
| "TransformerDoesNotExistException"
| "VersioningDisabledException"
| "TopologyNodeDownException"
| "AllTopologyNodesDownException"
| "BadResponseException"
| "ChangeProcessingException"
| "CommandExecutionException"
| "NoLeaderException"
| "CompilationException"
| "ConflictException"
| "DatabaseConcurrentLoadTimeoutException"
| "DatabaseDisabledException"
| "DatabaseLoadFailureException"
| "DatabaseNotFoundException"
| "NotSupportedOsException"
| "SecurityException"
| "ServerLoadFailureException"
| "UnsuccessfulRequestException"
| "CriticalIndexingException"
| "IndexAnalyzerException"
| "IndexCorruptionException"
| "IndexOpenException"
| "IndexWriteException"
| "IndexWriterCreationException"
| "StorageException"
| "StreamDisposedException"
| "LowMemoryException"
| "IncorrectDllException"
| "DiskFullException"
| "InvalidJournalFlushRequestException"
| "QuotaException"
| "VoronUnrecoverableErrorException"
| "NonDurableFileSystemException"
| "AggregateException";