// typings
export {AbstractCallback, EntityKeyCallback, EntityCallback, EntitiesArrayCallback, EntitiesCountCallback} from './Utility/Callbacks';
export {PromiseThenable, PromiseResolver, PromiseResolve, PromiseReject} from './Utility/PromiseResolver';
export {DocumentID, DocumentKey, IDocument} from './Documents/IDocument';
export {IDocumentStore} from './Documents/IDocumentStore';
export {IDocumentSession} from './Documents/Session/IDocumentSession';
export {IDocumentQueryConditions} from './Documents/Session/IDocumentQueryConditions';
export {IDocumentQuery} from './Documents/Session/IDocumentQuery';
export {EscapeQueryOption, EscapeQueryOptions} from './Documents/Session/EscapeQueryOptions';
export {IHiloKeyGenerator} from './Hilo/IHiloKeyGenerator';
export {RequestMethods, RequestMethod} from './Http/Request/RequestMethod';
export {QueryOperators, QueryOperator} from './Documents/Session/QueryOperator';
export {FieldIndexingOption, FieldIndexingOptions} from './Database/Indexes/FieldIndexingOption';
export {IndexLockMode, IndexLockModes} from './Database/Indexes/IndexLockMode';
export {SortOption, SortOptions} from './Database/Indexes/SortOption';
export {FieldTermVectorOption, FieldTermVectorOptions} from './Database/Indexes/FieldTermVectorOption';
export {IndexPriority, IndexPriorities} from './Database/Indexes/IndexPriority';
export {ReadBehavior, ReadBehaviors} from './Documents/Conventions/ReadBehavior';
export {WriteBehavior, WriteBehaviors} from './Documents/Conventions/WriteBehavior';
export {StatusCode, StatusCodes} from './Http/Response/StatusCode';
export {IMetadata, Metadata} from './Database/Metadata';
export {ILockDoneCallback, ILockCallback} from './Lock/LockCallbacks';
export {IHashCollection} from './Utility/IHashCollection';
export {IOptionsSet} from './Utility/IOptionsSet';
export {IJsonSerializable} from './Json/IJsonSerializable';
export {IRavenCommandResponse} from './Database/IRavenCommandResponse';
export {IHeaders} from './Http/IHeaders';
export {IResponse, IResponseBody} from './Http/Response/IResponse';

// classes
export {RavenException, InvalidOperationException, ErrorResponseException, DocumentDoesNotExistsException, NonUniqueObjectException, FetchConcurrencyException, ArgumentOutOfRangeException, DatabaseDoesNotExistException, AuthorizationException, IndexDoesNotExistException, TimeoutException} from './Database/DatabaseExceptions';
export {IHash, Hash} from './Utility/Hash';
export {RavenCommand} from './Database/RavenCommand';
export {GetDocumentCommand} from './Database/Commands/GetDocumentCommand';
export {DeleteDocumentCommand} from './Database/Commands/DeleteDocumentCommand';
export {PutDocumentCommand} from './Database/Commands/PutDocumentCommand';
export {QueryCommand} from './Database/Commands/QueryCommand';
export {GetTopologyCommand} from './Database/Commands/GetTopologyCommand';
export {GetOperationStateCommand} from './Database/Commands/GetOperationStateCommand';
export {RavenCommandData} from './Database/RavenCommandData';
export {PutCommandData} from './Database/Commands/Data/PutCommandData';
export {DeleteCommandData} from './Database/Commands/Data/DeleteCommandData';
export {QueryOperationOptions} from './Database/Operations/QueryOperationOptions';
export {Operations} from './Database/Operations/Operations';
export {Serializer} from './Json/Serializer';
export {Document} from './Documents/Document';
export {DocumentStore} from './Documents/DocumentStore';
export {DocumentSession} from './Documents/Session/DocumentSession';
export {DocumentQuery} from './Documents/Session/DocumentQuery';
export {DocumentConventions} from './Documents/Conventions/DocumentConventions';
export {IndexDefinition} from './Database/Indexes/IndexDefinition';
export {IndexFieldOptions} from './Database/Indexes/IndexFieldOptions';
export {IndexQuery} from './Database/Indexes/IndexQuery';
export {ServerNode} from './Http/ServerNode';
export {Topology} from './Http/Topology';
export {QueryString} from './Http/QueryString';
export {Lock} from './Lock/Lock';
export {DateUtil} from './Utility/DateUtil';
export {StringUtil} from './Utility/StringUtil';
export {ArrayUtil} from './Utility/ArrayUtil';
export {RequestsExecutor} from './Http/Request/RequestsExecutor';
export {PatchRequest} from './Http/Request/PatchRequest';
export {HiloRangeValue} from './Hilo/HiloRangeValue';
export {AbstractHiloKeyGenerator} from './Hilo/AbstractHiloKeyGenerator';
export {HiloKeyGenerator} from './Hilo/HiloKeyGenerator';
export {HiloMultiDatabaseKeyGenerator} from './Hilo/HiloMultiDatabaseKeyGenerator';
export {HiloMultiTypeKeyGenerator} from './Hilo/HiloMultiTypeKeyGenerator';
export {HiloNextCommand} from './Hilo/Commands/HiloNextCommand';
export {HiloReturnCommand} from './Hilo/Commands/HiloReturnCommand';

declare var uuid: Function;
declare var moment: Function;
declare var module: { exports: any };
declare class AsyncLock{ acquire: any };